### ISSUE TITLE
"DeprecationWarning: context.fix is being deprecated" with latest stylelint 16.8.2

### ISSUE THREAD

**Issue by sebbayer** [stylelint-stylistic/stylelint-stylistic#36] opened 2024-08-16 16:44 UTC
### What minimal example or steps are needed to reproduce the bug?

1. Install this package in latest version 3.0.0 or 2.0.0
2. Install stylelint 16.8.2
3. Enable the plugin in stylelint config
4. Run stylelint

### What minimal configuration is needed to reproduce the bug?

```json
  {
    "@nuxtjs/stylelint-module": "^5.2.0",
    "@stylistic/stylelint-plugin": "^3.0.0",
    "postcss-html": "^1.6.0",
    "stylelint": "16.8.2",
    "stylelint-config-standard-scss": "^13.0.0",
    "stylelint-config-standard-vue": "^1.0.0",
    "stylelint-declaration-strict-value": "^1.10.4",
    "stylelint-order": "^6.0.4"
  }
```

### How did you run Stylelint?

```yarn stylelint **/*.vue```

### Which Stylelint-related dependencies are you using?

```json 
  {
    "@nuxtjs/stylelint-module": "^5.2.0",
    "@stylistic/stylelint-plugin": "^2.0.0",
    "postcss-html": "^1.6.0",
    "stylelint": "16.8.2",
    "stylelint-config-standard-scss": "^13.0.0",
    "stylelint-config-standard-vue": "^1.0.0",
    "stylelint-declaration-strict-value": "^1.10.4",
    "stylelint-order": "^6.0.4"
  }
```

### What did you expect to happen?

No deprecation warnings.

### What actually happened?

Lots of warnings (which Nuxt somehow counts as errors) in this format

> (node:29599) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "@stylistic/value-list-max-empty-lines" instead.

This is repeated for every rule that is used.

### Do you have a proposal to fix the bug?

The mentioned `fix` callback probably has to be added to each rule.

**Comment by firefoxic** [comment] 2024-08-16 19:48
Thanks for the report. Already working on it.

**Comment by firefoxic** [comment] 2024-08-16 19:51
Closing as duplicate of #35

**Closed by firefoxic** 2024-08-16 19:51 UTC
Labels: rel: upstream
