### ISSUE TITLE
Is there any rules about moving the declaration above the nested rule ?

### ISSUE THREAD

**Issue by l-outsider** [stylelint-stylistic/stylelint-stylistic#34] opened 2024-07-16 09:09 UTC
### Describe the documentation issue

sass in my project report some warning

> Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

because the following structure:

```scss
.parent {
    .child {
        // some property
    }

    width: 100px;
}
```

it means i must move css declarations of parent above nested scss, like this:

```scss
.parent {
    width: 100px;

    .child {
        // some property
    }
}
```

so, I try to find some rules to achieve this structure. thanks.

### What solution would you like to see?

Are there any existing rules that can achieve this restriction? If not, can it be supported?

**Comment by MorevM** [comment] 2024-07-16 12:48
I think this issue is out of scope this plugin.
Per [the docs](https://github.com/stylelint-stylistic/stylelint-stylistic/blob/main/docs/developer-guide/rules.md) all rules should be for standard CSS syntax, while the issue is (mostly) related to SCSS syntax.

Perhaps I don't fully understand the CSS working group's motivation for [doing it this way](https://sass-lang.com/documentation/breaking-changes/mixed-decls/#the-story-so-far), and it might be worth considering a new rule that would collect nested declarations on top of the selector. 
This requires more research and I'd be happy to hear other opinions, but at first glance I have a feeling that this shouldn't be handled within this package after all. It's not even a stylistic thing - it affects the final result.

Currently, you can achieve the desired result by using [the `order` rule in the `stylelint-order` package](https://github.com/hudochenkov/stylelint-order/blob/master/rules/order/README.md).

**Comment by Mouvedia** [comment] 2024-07-16 15:49
This is not stylistic because the resulting "fix" wouldn't have the same specificity once hoisted.
i.e. if it was a rule on another repository/package it shouldn't be fixable

**Comment by Mouvedia** [comment] 2024-07-16 15:52
This is not stylistic because the resulting "fix" is not equivalent once hoisted.
i.e. if it was a rule on another repository/package it shouldn't be fixable

**Comment by firefoxic** [comment] 2024-07-16 17:16
Absolutely agree, it's not stylistic formatting, it's an aspect of syntax.

I'm not even sure that such a rule should be in stylelint itself. Haven't delved into it, but perhaps stylelint-scss/stylelint-scss#1020 would be more relevant to you, @LLwyct.

**Comment by LLwyct** [comment] 2024-07-16 18:02
Thanks for your response. That is right.
I initially wanted this rule because I was not clear about the difference between the two placements, but now I understand.

But for my team, we may never encounter this new CSS handling method, so in order to ensure consistency in the compilation results, I will try the order rule mentioned by @MorevM to restrict the writing style of team code.

**Closed by LLwyct** 2024-07-16 18:02 UTC
